### ISSUE TITLE
Recortes

### ISSUE THREAD

**Issue by cassiandrei** [pratiqueobi/pratiqueobiweb#2]
Ana: provas anos ímpares
Cassiano: provas anos pares

Organização:
recortes/ano/f1n1/problema1/
- enunciado.png
- titulo.png
- regras.png
- problema.png
- questao1.png
- questoes.png

**Comment by anaveroneze** [comment]
Recortes feitos.
- título
- enunciado
- regras
- imagem do problema
- questões
- imagem das questões
